### ISSUE TITLE
The entire code is the same colour

### ISSUE THREAD

**Issue by zanlib0** [blackxparade/Tycho-Dark-Syntax#1]
```
Atom    : 1.12.7
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

I'm on elementary Loki and this is how Atom syntax looks with the theme enabled.

![alt](http://pix.toile-libre.org/upload/original/1488866541.png)

**Comment by krtibo** [comment]
That's weird, I typed in your code to my Atom and it works perfectly. 

* Do you have the [language-javascript](https://atom.io/packages/language-javascript) package installed? It seems like yout Atom don't recognize JS code. 
* Is it working with another syntax themes?

**Comment by zanlib0** [comment]
I have the package installed and it is working without a problem with other syntax themes (tested with `nord-dark-syntax`)

**Comment by krtibo** [comment]
One more thing I can think of is that I see you're using version 1.12.7. I remember that I had to update the theme once, because some of the CSS selectors have changed from version 1.13+. That was a breaking change, and Atom notified me that some of the used selectors were deprecated.
So basically I think if you update (reinstall) Atom, the problem will be gone.

**Comment by zanlib0** [comment]
Ah, yeah, it seems like it fixed the issue. Thanks a lot :)

**Comment by krtibo** [comment]
Great! Thank you for reporting this issue!
